/**
 * Data loading utilities for BotBourse.
 *
 * Reads from public/data/ JSON files generated by the Python pipeline.
 * Falls back to mock data if the pipeline hasn't been run yet.
 *
 * IMPORTANT: We use explicit file paths (not dynamic path.join with variables)
 * for the small JSON files so that Next.js/Turbopack only traces exactly
 * the files needed. For large directories (prices/, features/), we delegate
 * to dedicated API routes to avoid bundling 250+ MB into every function.
 */

import { promises as fs } from "fs";
import path from "path";
import type { Asset, Prediction, WatchlistItem, MarketIndex, OHLCData } from "./types";

// ─── Helpers ───

async function readFileContent(filePath: string): Promise<string | null> {
    try {
        return await fs.readFile(filePath, "utf-8");
    } catch {
        return null;
    }
}

// ─── Assets ───

export async function getAssets(): Promise<Asset[]> {
    const raw = await readFileContent(
        path.join(process.cwd(), "public", "data", "assets.json")
    );
    if (!raw) {
        const { MOCK_ASSETS } = await import("./mock-data");
        return MOCK_ASSETS;
    }
    const data = JSON.parse(raw) as Record<string, unknown>[];
    return data.map(normalizeAsset);
}

export async function getAssetByTicker(ticker: string): Promise<Asset | null> {
    const assets = await getAssets();
    return assets.find((a) => a.ticker === ticker) ?? null;
}

function normalizeAsset(raw: Record<string, unknown>): Asset {
    return {
        ticker: String(raw.ticker ?? ""),
        name: String(raw.name ?? ""),
        assetType: (raw.assetType as Asset["assetType"]) ?? "stock",
        exchange: String(raw.exchange ?? ""),
        sector: (raw.sector as Asset["sector"]) ?? "Diversified",
        region: (raw.region as Asset["region"]) ?? "US",
        currency: String(raw.currency ?? "USD"),
        price: Number(raw.price ?? 0),
        change: Number(raw.change ?? 0),
        changePercent: Number(raw.changePercent ?? 0),
        // Stock fields
        marketCap: raw.marketCap != null ? Number(raw.marketCap) : undefined,
        peRatio: raw.peRatio != null ? Number(raw.peRatio) : undefined,
        dividendYield: raw.dividendYield != null ? Number(raw.dividendYield) : undefined,
        volume: raw.volume != null ? Number(raw.volume) : undefined,
        // ETF fields
        indexTracked: raw.indexTracked != null ? String(raw.indexTracked) : undefined,
        ter: raw.ter != null ? Number(raw.ter) : undefined,
        domicile: raw.domicile != null ? String(raw.domicile) : undefined,
        etfCategory: raw.etfCategory != null ? String(raw.etfCategory) : undefined,
    };
}

// ─── Indices ───

export async function getIndices(): Promise<MarketIndex[]> {
    const raw = await readFileContent(
        path.join(process.cwd(), "public", "data", "indices.json")
    );
    if (!raw) {
        const { MOCK_INDICES } = await import("./mock-data");
        return MOCK_INDICES;
    }
    return JSON.parse(raw) as MarketIndex[];
}

// ─── Predictions ───

export async function getPredictions(): Promise<Prediction[]> {
    const raw = await readFileContent(
        path.join(process.cwd(), "public", "data", "predictions.json")
    );
    if (!raw) {
        const { MOCK_PREDICTIONS } = await import("./mock-data");
        return MOCK_PREDICTIONS;
    }
    const data = JSON.parse(raw) as Record<string, unknown>[];
    return data.map(normalizePrediction);
}

function normalizePrediction(raw: Record<string, unknown>): Prediction {
    const expectedReturn = Number(raw.expectedReturn ?? 0);
    const confidence = Number(raw.confidence ?? 0.5);

    let confidenceLevel: Prediction["confidenceLevel"] = "medium";
    if (raw.confidenceLevel) {
        confidenceLevel = raw.confidenceLevel as Prediction["confidenceLevel"];
    } else if (confidence >= 0.65) {
        confidenceLevel = "high";
    } else if (confidence < 0.45) {
        confidenceLevel = "low";
    }

    let trendLabel: Prediction["trendLabel"] = "neutral";
    if (raw.trendLabel) {
        trendLabel = raw.trendLabel as Prediction["trendLabel"];
    } else if (expectedReturn > 0.005) {
        trendLabel = "bullish";
    } else if (expectedReturn < -0.005) {
        trendLabel = "bearish";
    }

    return {
        ticker: String(raw.ticker ?? ""),
        name: String(raw.name ?? ""),
        horizon: (raw.horizon as Prediction["horizon"]) ?? "short",
        expectedReturn,
        riskScore: (Number(raw.riskScore ?? 3) as Prediction["riskScore"]),
        confidence,
        confidenceLevel,
        trendLabel,
        sector: (raw.sector as Prediction["sector"]) ?? "Diversified",
        region: (raw.region as Prediction["region"]) ?? "US",
        assetType: (raw.assetType as Prediction["assetType"]) ?? "stock",
    };
}

// ─── Watchlist ───

export async function getWatchlist(): Promise<WatchlistItem[]> {
    const raw = await readFileContent(
        path.join(process.cwd(), "public", "data", "watchlist.json")
    );
    if (!raw) {
        const { MOCK_WATCHLIST } = await import("./mock-data");
        return MOCK_WATCHLIST;
    }
    return JSON.parse(raw) as WatchlistItem[];
}

// ─── Prices ───
//
// Prices are served from a dedicated API route (/api/prices/[ticker])
// to avoid bundling the entire prices/ directory (250+ MB) into every
// serverless function. On the server side during SSR, we use a direct
// filesystem read with an explicit path construction.

export async function getPrices(ticker: string): Promise<OHLCData[]> {
    const safeTicker = ticker.replace(/\./g, "_").replace(/\^/g, "");

    // Server-side: read directly from filesystem
    try {
        const filePath = path.join(
            process.cwd(), "public", "data", "prices", `${safeTicker}.json`
        );
        const raw = await fs.readFile(filePath, "utf-8");
        return JSON.parse(raw) as OHLCData[];
    } catch {
        // Fallback to mock data
        const { generateMockOHLC } = await import("./mock-data");
        return generateMockOHLC(365, 100);
    }
}

// ─── Screener ───

export async function getScreenerData(): Promise<Record<string, unknown>[]> {
    const raw = await readFileContent(
        path.join(process.cwd(), "public", "data", "screener.json")
    );
    if (!raw) return [];
    return JSON.parse(raw) as Record<string, unknown>[];
}

// ─── Features (Technical Indicators) ───
//
// Same approach as prices: dedicated API route avoids bundling features/.

export async function getFeatures(ticker: string): Promise<Record<string, number | string | null> | null> {
    const safeTicker = ticker.replace(/\./g, "_").replace(/\^/g, "");

    try {
        const filePath = path.join(
            process.cwd(), "public", "data", "features", `${safeTicker}.json`
        );
        const raw = await fs.readFile(filePath, "utf-8");
        return JSON.parse(raw) as Record<string, number | string | null>;
    } catch {
        return null;
    }
}

// ─── Pipeline Metadata ───

export async function getPipelineMeta(): Promise<Record<string, unknown> | null> {
    const raw = await readFileContent(
        path.join(process.cwd(), "public", "data", "meta.json")
    );
    if (!raw) return null;
    return JSON.parse(raw) as Record<string, unknown>;
}

