/**
 * Data loading utilities for BotBourse.
 *
 * Reads from public/data/ JSON files generated by the Python pipeline.
 * Falls back to mock data if the pipeline hasn't been run yet.
 */

import { promises as fs } from "fs";
import path from "path";
import type { Asset, Prediction, WatchlistItem, MarketIndex, OHLCData } from "./types";

const DATA_DIR = path.join(process.cwd(), "public", "data");

async function readJSON<T>(filename: string): Promise<T | null> {
    try {
        const filePath = path.join(DATA_DIR, filename);
        const raw = await fs.readFile(filePath, "utf-8");
        return JSON.parse(raw) as T;
    } catch {
        return null;
    }
}

// ─── Assets ───

export async function getAssets(): Promise<Asset[]> {
    const data = await readJSON<Record<string, unknown>[]>("assets.json");
    if (!data) {
        // Fallback to mock
        const { MOCK_ASSETS } = await import("./mock-data");
        return MOCK_ASSETS;
    }
    return data.map(normalizeAsset);
}

export async function getAssetByTicker(ticker: string): Promise<Asset | null> {
    const assets = await getAssets();
    return assets.find((a) => a.ticker === ticker) ?? null;
}

function normalizeAsset(raw: Record<string, unknown>): Asset {
    return {
        ticker: String(raw.ticker ?? ""),
        name: String(raw.name ?? ""),
        assetType: (raw.assetType as Asset["assetType"]) ?? "stock",
        exchange: String(raw.exchange ?? ""),
        sector: (raw.sector as Asset["sector"]) ?? "Diversified",
        region: (raw.region as Asset["region"]) ?? "US",
        currency: String(raw.currency ?? "USD"),
        price: Number(raw.price ?? 0),
        change: Number(raw.change ?? 0),
        changePercent: Number(raw.changePercent ?? 0),
        // Stock fields
        marketCap: raw.marketCap != null ? Number(raw.marketCap) : undefined,
        peRatio: raw.peRatio != null ? Number(raw.peRatio) : undefined,
        dividendYield: raw.dividendYield != null ? Number(raw.dividendYield) : undefined,
        volume: raw.volume != null ? Number(raw.volume) : undefined,
        // ETF fields
        indexTracked: raw.indexTracked != null ? String(raw.indexTracked) : undefined,
        ter: raw.ter != null ? Number(raw.ter) : undefined,
        domicile: raw.domicile != null ? String(raw.domicile) : undefined,
        etfCategory: raw.etfCategory != null ? String(raw.etfCategory) : undefined,
    };
}

// ─── Indices ───

export async function getIndices(): Promise<MarketIndex[]> {
    const data = await readJSON<MarketIndex[]>("indices.json");
    if (!data) {
        const { MOCK_INDICES } = await import("./mock-data");
        return MOCK_INDICES;
    }
    return data;
}

// ─── Predictions ───

export async function getPredictions(): Promise<Prediction[]> {
    const data = await readJSON<Record<string, unknown>[]>("predictions.json");
    if (!data) {
        const { MOCK_PREDICTIONS } = await import("./mock-data");
        return MOCK_PREDICTIONS;
    }
    return data.map(normalizePrediction);
}

function normalizePrediction(raw: Record<string, unknown>): Prediction {
    const expectedReturn = Number(raw.expectedReturn ?? 0);
    const confidence = Number(raw.confidence ?? 0.5);

    let confidenceLevel: Prediction["confidenceLevel"] = "medium";
    if (raw.confidenceLevel) {
        confidenceLevel = raw.confidenceLevel as Prediction["confidenceLevel"];
    } else if (confidence >= 0.65) {
        confidenceLevel = "high";
    } else if (confidence < 0.45) {
        confidenceLevel = "low";
    }

    let trendLabel: Prediction["trendLabel"] = "neutral";
    if (raw.trendLabel) {
        trendLabel = raw.trendLabel as Prediction["trendLabel"];
    } else if (expectedReturn > 0.005) {
        trendLabel = "bullish";
    } else if (expectedReturn < -0.005) {
        trendLabel = "bearish";
    }

    return {
        ticker: String(raw.ticker ?? ""),
        name: String(raw.name ?? ""),
        horizon: (raw.horizon as Prediction["horizon"]) ?? "short",
        expectedReturn,
        riskScore: (Number(raw.riskScore ?? 3) as Prediction["riskScore"]),
        confidence,
        confidenceLevel,
        trendLabel,
        sector: (raw.sector as Prediction["sector"]) ?? "Diversified",
        region: (raw.region as Prediction["region"]) ?? "US",
        assetType: (raw.assetType as Prediction["assetType"]) ?? "stock",
    };
}

// ─── Watchlist ───

export async function getWatchlist(): Promise<WatchlistItem[]> {
    const data = await readJSON<WatchlistItem[]>("watchlist.json");
    if (!data) {
        const { MOCK_WATCHLIST } = await import("./mock-data");
        return MOCK_WATCHLIST;
    }
    return data;
}

// ─── Prices ───

export async function getPrices(ticker: string): Promise<OHLCData[]> {
    const safeTicker = ticker.replace(/\./g, "_").replace(/\^/g, "");
    const data = await readJSON<OHLCData[]>(`prices/${safeTicker}.json`);
    if (!data) {
        // Generate mock data as fallback
        const { generateMockOHLC } = await import("./mock-data");
        return generateMockOHLC(365, 100);
    }
    return data;
}

// ─── Screener ───

export async function getScreenerData(): Promise<Record<string, unknown>[]> {
    const data = await readJSON<Record<string, unknown>[]>("screener.json");
    return data ?? [];
}

// ─── Features (Technical Indicators) ───

export async function getFeatures(ticker: string): Promise<Record<string, number | string | null> | null> {
    const safeTicker = ticker.replace(/\./g, "_").replace(/\^/g, "");
    return readJSON(`features/${safeTicker}.json`);
}

// ─── Pipeline Metadata ───

export async function getPipelineMeta(): Promise<Record<string, unknown> | null> {
    return readJSON("meta.json");
}
