import { Metadata } from "next";
import { MODEL_VERSION } from "@/lib/constants";

export const metadata: Metadata = {
    title: "Legal & Disclaimer",
    description: "Legal information, disclaimers, and model methodology for BotBourse.",
};

export default function LegalPage() {
    return (
        <div className="px-4 sm:px-6 py-8 md:py-16" style={{ maxWidth: 800, margin: "0 auto" }}>
            <h1
                className="text-3xl md:text-4xl font-bold tracking-tighter mb-8"
                style={{ color: "var(--text-primary)" }}
            >
                Legal & Disclaimer
            </h1>

            <div className="space-y-8">
                <Section title="General Disclaimer">
                    <p>
                        BotBourse provides model-generated market analysis for stocks and ETFs
                        for <strong>informational and educational purposes only</strong>. Nothing
                        on this platform constitutes investment advice, a recommendation to buy or
                        sell any financial instrument, or an offer of any regulated financial service.
                    </p>
                    <p>
                        All model outputs, including expected returns, risk scores, trend labels,
                        and watchlist signals, are generated by quantitative algorithms based on
                        historical data. <strong>Past performance and model estimates do not
                            guarantee future results.</strong>
                    </p>
                </Section>

                <Section title="Nature of Predictions">
                    <p>
                        The predictions displayed on this platform are outputs of machine learning
                        models trained on publicly available historical market data. They represent
                        statistical estimates, not certainties. Key characteristics:
                    </p>
                    <ul className="list-disc pl-5 space-y-1.5 mt-2">
                        <li>Short-term estimates (~30 days) have inherently limited accuracy due to market noise.</li>
                        <li>Medium-term estimates (~12 months) rely on factor-based models with moderate historical signal.</li>
                        <li>Long-term estimates (~3-5 years) represent structural views based on valuation and sector heuristics.</li>
                        <li>Confidence levels indicate the model&apos;s own uncertainty, not a guarantee of correctness.</li>
                        <li>Risk scores are composite metrics based on volatility, drawdown, and correlation data.</li>
                    </ul>
                </Section>

                <Section title="Model Methodology">
                    <p>
                        Current model version: <span className="num font-semibold">{MODEL_VERSION}</span>
                    </p>
                    <p className="mt-2">
                        <strong>Short-term (~30 days):</strong> LightGBM 3-class gradient boosting classifier
                        predicting directional movement (positive / neutral / negative). Trained with
                        walk-forward validation on 5 years of cross-sectional data across 166 assets.
                        Expected return is derived from class probabilities weighted by typical class returns.
                    </p>
                    <p className="mt-2">
                        <strong>Medium-term (~12 months):</strong> LightGBM regression model predicting
                        log-returns over a 252 trading day horizon. Uses the same feature set with
                        regularization tuned for longer-horizon noise. Confidence is calibrated via
                        signal-to-noise ratio against recent volatility.
                    </p>
                    <p className="mt-2">
                        <strong>Long-term (~3 years):</strong> Rule-based heuristic scoring system
                        combining trend (price vs 200-day MA), momentum, volatility, drawdown, RSI
                        stability, and trend strength (ADX). Confidence is capped at &ldquo;medium&rdquo; by
                        design, as long-term prediction accuracy is inherently limited.
                    </p>
                    <p className="mt-2">
                        <strong>Feature set:</strong> RSI(14), MACD histogram, Bollinger Band position,
                        Stochastic K, ADX, 20/50/200-day SMA crossovers, 5/20/60-day returns,
                        20/60-day annualized volatility, volume ratio, and drawdown.
                    </p>
                    <p className="mt-2">
                        Models are retrained periodically and predictions are updated via batch
                        processing. The platform does not perform real-time inference or high-frequency
                        trading analysis.
                    </p>
                </Section>

                <Section title="Regulatory Notice">
                    <p>
                        This platform does <strong>not</strong> constitute a regulated investment service
                        under MiFID II (Directive 2014/65/EU) or under the supervision of the
                        Autorit&eacute; des March&eacute;s Financiers (AMF). The operator of this
                        platform is not a licensed investment advisor, portfolio manager, or financial
                        intermediary.
                    </p>
                    <p className="mt-2">
                        Users should consult with a qualified financial professional before making
                        any investment decisions. BotBourse encourages diversification, risk awareness,
                        and careful consideration of individual financial circumstances.
                    </p>
                </Section>

                <Section title="Data Sources">
                    <p>
                        Market data is sourced from publicly available APIs and data providers.
                        While we strive for accuracy, we do not guarantee the completeness,
                        timeliness, or accuracy of any data displayed. Prices may be delayed
                        and should not be used for real-time trading decisions.
                    </p>
                </Section>

                <Section title="Limitation of Liability">
                    <p>
                        BotBourse, its operators, and contributors shall not be held liable for
                        any financial losses, damages, or other consequences resulting from the
                        use of information provided on this platform. Users access and use this
                        platform entirely at their own risk.
                    </p>
                </Section>
            </div>
        </div>
    );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
    return (
        <div
            className="pb-8"
            style={{ borderBottom: "1px solid var(--border)" }}
        >
            <h2
                className="text-lg font-semibold tracking-tight mb-3"
                style={{ color: "var(--text-primary)" }}
            >
                {title}
            </h2>
            <div
                className="text-sm leading-relaxed space-y-3"
                style={{ color: "var(--text-secondary)", maxWidth: "65ch" }}
            >
                {children}
            </div>
        </div>
    );
}
