"""
BotBourse Pipeline Configuration

Defines the universe of assets to track, horizons, and output paths.
"""

import os
from pathlib import Path

# ─── Paths ───
BASE_DIR = Path(__file__).parent
DATA_DIR = BASE_DIR.parent / "public" / "data"  # Output into Next.js public/ for easy access
PRICES_DIR = DATA_DIR / "prices"
FEATURES_DIR = DATA_DIR / "features"

# Ensure directories exist
for d in [DATA_DIR, PRICES_DIR, FEATURES_DIR]:
    d.mkdir(parents=True, exist_ok=True)

# ─── Asset Universe ───
# ~150 stocks: US large/mid cap + European large cap (FR, DE, NL, UK, CH, DK, ES, IT, BE, SE)
# ~40 ETFs: broad, sector, regional, thematic — focus on European-domiciled UCITS

STOCKS = {
    # ══════════════════════════════════════════
    #  US — Large Cap (~50)
    # ══════════════════════════════════════════
    "AAPL":   {"name": "Apple Inc.", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "MSFT":   {"name": "Microsoft Corp.", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "NVDA":   {"name": "NVIDIA Corp.", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "AMZN":   {"name": "Amazon.com Inc.", "sector": "Consumer", "region": "US", "exchange": "NASDAQ"},
    "GOOGL":  {"name": "Alphabet Inc.", "sector": "Communication", "region": "US", "exchange": "NASDAQ"},
    "META":   {"name": "Meta Platforms Inc.", "sector": "Communication", "region": "US", "exchange": "NASDAQ"},
    "TSLA":   {"name": "Tesla Inc.", "sector": "Consumer", "region": "US", "exchange": "NASDAQ"},
    "JPM":    {"name": "JPMorgan Chase & Co.", "sector": "Finance", "region": "US", "exchange": "NYSE"},
    "V":      {"name": "Visa Inc.", "sector": "Finance", "region": "US", "exchange": "NYSE"},
    "JNJ":    {"name": "Johnson & Johnson", "sector": "Healthcare", "region": "US", "exchange": "NYSE"},
    "UNH":    {"name": "UnitedHealth Group", "sector": "Healthcare", "region": "US", "exchange": "NYSE"},
    "XOM":    {"name": "Exxon Mobil Corp.", "sector": "Energy", "region": "US", "exchange": "NYSE"},
    "PG":     {"name": "Procter & Gamble Co.", "sector": "Consumer", "region": "US", "exchange": "NYSE"},
    "HD":     {"name": "Home Depot Inc.", "sector": "Consumer", "region": "US", "exchange": "NYSE"},
    "MA":     {"name": "Mastercard Inc.", "sector": "Finance", "region": "US", "exchange": "NYSE"},
    "AVGO":   {"name": "Broadcom Inc.", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "COST":   {"name": "Costco Wholesale", "sector": "Consumer", "region": "US", "exchange": "NASDAQ"},
    "ABBV":   {"name": "AbbVie Inc.", "sector": "Healthcare", "region": "US", "exchange": "NYSE"},
    "CRM":    {"name": "Salesforce Inc.", "sector": "Technology", "region": "US", "exchange": "NYSE"},
    "AMD":    {"name": "Advanced Micro Devices", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "NFLX":   {"name": "Netflix Inc.", "sector": "Communication", "region": "US", "exchange": "NASDAQ"},
    "LIN":    {"name": "Linde plc", "sector": "Materials", "region": "US", "exchange": "NYSE"},
    "PANW":   {"name": "Palo Alto Networks", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "INTC":   {"name": "Intel Corp.", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "DIS":    {"name": "Walt Disney Co.", "sector": "Communication", "region": "US", "exchange": "NYSE"},
    "KO":     {"name": "Coca-Cola Co.", "sector": "Consumer", "region": "US", "exchange": "NYSE"},
    "PEP":    {"name": "PepsiCo Inc.", "sector": "Consumer", "region": "US", "exchange": "NASDAQ"},
    "MRK":    {"name": "Merck & Co.", "sector": "Healthcare", "region": "US", "exchange": "NYSE"},
    "WMT":    {"name": "Walmart Inc.", "sector": "Consumer", "region": "US", "exchange": "NYSE"},
    "CSCO":   {"name": "Cisco Systems", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "ORCL":   {"name": "Oracle Corp.", "sector": "Technology", "region": "US", "exchange": "NYSE"},
    "ACN":    {"name": "Accenture plc", "sector": "Technology", "region": "US", "exchange": "NYSE"},
    "IBM":    {"name": "IBM Corp.", "sector": "Technology", "region": "US", "exchange": "NYSE"},
    "NOW":    {"name": "ServiceNow Inc.", "sector": "Technology", "region": "US", "exchange": "NYSE"},
    "QCOM":   {"name": "Qualcomm Inc.", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "GS":     {"name": "Goldman Sachs Group", "sector": "Finance", "region": "US", "exchange": "NYSE"},
    "MS":     {"name": "Morgan Stanley", "sector": "Finance", "region": "US", "exchange": "NYSE"},
    "BAC":    {"name": "Bank of America Corp.", "sector": "Finance", "region": "US", "exchange": "NYSE"},
    "BLK":    {"name": "BlackRock Inc.", "sector": "Finance", "region": "US", "exchange": "NYSE"},
    "PYPL":   {"name": "PayPal Holdings", "sector": "Finance", "region": "US", "exchange": "NASDAQ"},
    "PFE":    {"name": "Pfizer Inc.", "sector": "Healthcare", "region": "US", "exchange": "NYSE"},
    "LLY":    {"name": "Eli Lilly & Co.", "sector": "Healthcare", "region": "US", "exchange": "NYSE"},
    "TMO":    {"name": "Thermo Fisher Scientific", "sector": "Healthcare", "region": "US", "exchange": "NYSE"},
    "CVX":    {"name": "Chevron Corp.", "sector": "Energy", "region": "US", "exchange": "NYSE"},
    "COP":    {"name": "ConocoPhillips", "sector": "Energy", "region": "US", "exchange": "NYSE"},
    "NEE":    {"name": "NextEra Energy", "sector": "Utilities", "region": "US", "exchange": "NYSE"},
    "CAT":    {"name": "Caterpillar Inc.", "sector": "Industrials", "region": "US", "exchange": "NYSE"},
    "BA":     {"name": "Boeing Co.", "sector": "Industrials", "region": "US", "exchange": "NYSE"},
    "GE":     {"name": "GE Aerospace", "sector": "Industrials", "region": "US", "exchange": "NYSE"},
    "DE":     {"name": "Deere & Company", "sector": "Industrials", "region": "US", "exchange": "NYSE"},

    # ══════════════════════════════════════════
    #  France — CAC 40 & SBF 120 (~25)
    # ══════════════════════════════════════════
    "MC.PA":     {"name": "LVMH Moet Hennessy", "sector": "Consumer", "region": "Europe", "exchange": "Euronext Paris"},
    "OR.PA":     {"name": "L'Oreal SA", "sector": "Consumer", "region": "Europe", "exchange": "Euronext Paris"},
    "TTE.PA":    {"name": "TotalEnergies SE", "sector": "Energy", "region": "Europe", "exchange": "Euronext Paris"},
    "SAN.PA":    {"name": "Sanofi SA", "sector": "Healthcare", "region": "Europe", "exchange": "Euronext Paris"},
    "AIR.PA":    {"name": "Airbus SE", "sector": "Industrials", "region": "Europe", "exchange": "Euronext Paris"},
    "SU.PA":     {"name": "Schneider Electric", "sector": "Industrials", "region": "Europe", "exchange": "Euronext Paris"},
    "BNP.PA":    {"name": "BNP Paribas SA", "sector": "Finance", "region": "Europe", "exchange": "Euronext Paris"},
    "AI.PA":     {"name": "Air Liquide SA", "sector": "Materials", "region": "Europe", "exchange": "Euronext Paris"},
    "DG.PA":     {"name": "Vinci SA", "sector": "Industrials", "region": "Europe", "exchange": "Euronext Paris"},
    "BN.PA":     {"name": "Danone SA", "sector": "Consumer", "region": "Europe", "exchange": "Euronext Paris"},
    "RI.PA":     {"name": "Pernod Ricard SA", "sector": "Consumer", "region": "Europe", "exchange": "Euronext Paris"},
    "KER.PA":    {"name": "Kering SA", "sector": "Consumer", "region": "Europe", "exchange": "Euronext Paris"},
    "CAP.PA":    {"name": "Capgemini SE", "sector": "Technology", "region": "Europe", "exchange": "Euronext Paris"},
    "STM.PA":    {"name": "STMicroelectronics", "sector": "Technology", "region": "Europe", "exchange": "Euronext Paris"},
    "CS.PA":     {"name": "AXA SA", "sector": "Finance", "region": "Europe", "exchange": "Euronext Paris"},
    "GLE.PA":    {"name": "Societe Generale SA", "sector": "Finance", "region": "Europe", "exchange": "Euronext Paris"},
    "SGO.PA":    {"name": "Saint-Gobain SA", "sector": "Industrials", "region": "Europe", "exchange": "Euronext Paris"},
    "DSY.PA":    {"name": "Dassault Systemes SE", "sector": "Technology", "region": "Europe", "exchange": "Euronext Paris"},
    "HO.PA":     {"name": "Thales SA", "sector": "Industrials", "region": "Europe", "exchange": "Euronext Paris"},
    "EN.PA":     {"name": "Bouygues SA", "sector": "Industrials", "region": "Europe", "exchange": "Euronext Paris"},
    "VIV.PA":    {"name": "Vivendi SE", "sector": "Communication", "region": "Europe", "exchange": "Euronext Paris"},
    "ORA.PA":    {"name": "Orange SA", "sector": "Communication", "region": "Europe", "exchange": "Euronext Paris"},
    "RMS.PA":    {"name": "Hermes International", "sector": "Consumer", "region": "Europe", "exchange": "Euronext Paris"},
    "EL.PA":     {"name": "EssilorLuxottica SA", "sector": "Healthcare", "region": "Europe", "exchange": "Euronext Paris"},
    "SAF.PA":    {"name": "Safran SA", "sector": "Industrials", "region": "Europe", "exchange": "Euronext Paris"},

    # ══════════════════════════════════════════
    #  Germany — DAX (~15)
    # ══════════════════════════════════════════
    "SAP":       {"name": "SAP SE", "sector": "Technology", "region": "Europe", "exchange": "XETRA"},
    "SIE.DE":    {"name": "Siemens AG", "sector": "Industrials", "region": "Europe", "exchange": "XETRA"},
    "ALV.DE":    {"name": "Allianz SE", "sector": "Finance", "region": "Europe", "exchange": "XETRA"},
    "DTE.DE":    {"name": "Deutsche Telekom AG", "sector": "Communication", "region": "Europe", "exchange": "XETRA"},
    "MBG.DE":    {"name": "Mercedes-Benz Group", "sector": "Consumer", "region": "Europe", "exchange": "XETRA"},
    "BMW.DE":    {"name": "BMW AG", "sector": "Consumer", "region": "Europe", "exchange": "XETRA"},
    "BAS.DE":    {"name": "BASF SE", "sector": "Materials", "region": "Europe", "exchange": "XETRA"},
    "MUV2.DE":   {"name": "Munich Re", "sector": "Finance", "region": "Europe", "exchange": "XETRA"},
    "IFX.DE":    {"name": "Infineon Technologies", "sector": "Technology", "region": "Europe", "exchange": "XETRA"},
    "ADS.DE":    {"name": "Adidas AG", "sector": "Consumer", "region": "Europe", "exchange": "XETRA"},
    "DHL.DE":    {"name": "DHL Group", "sector": "Industrials", "region": "Europe", "exchange": "XETRA"},
    "RWE.DE":    {"name": "RWE AG", "sector": "Utilities", "region": "Europe", "exchange": "XETRA"},
    "VOW3.DE":   {"name": "Volkswagen AG", "sector": "Consumer", "region": "Europe", "exchange": "XETRA"},
    "DB1.DE":    {"name": "Deutsche Boerse AG", "sector": "Finance", "region": "Europe", "exchange": "XETRA"},
    "HEN3.DE":   {"name": "Henkel AG", "sector": "Consumer", "region": "Europe", "exchange": "XETRA"},

    # ══════════════════════════════════════════
    #  Netherlands — AEX (~8)
    # ══════════════════════════════════════════
    "ASML":      {"name": "ASML Holding NV", "sector": "Technology", "region": "Europe", "exchange": "Euronext Amsterdam"},
    "PHIA.AS":   {"name": "Koninklijke Philips", "sector": "Healthcare", "region": "Europe", "exchange": "Euronext Amsterdam"},
    "INGA.AS":   {"name": "ING Group NV", "sector": "Finance", "region": "Europe", "exchange": "Euronext Amsterdam"},
    "UNA.AS":    {"name": "Unilever NV", "sector": "Consumer", "region": "Europe", "exchange": "Euronext Amsterdam"},
    "AD.AS":     {"name": "Ahold Delhaize NV", "sector": "Consumer", "region": "Europe", "exchange": "Euronext Amsterdam"},
    "WKL.AS":    {"name": "Wolters Kluwer NV", "sector": "Communication", "region": "Europe", "exchange": "Euronext Amsterdam"},
    "PRX.AS":    {"name": "Prosus NV", "sector": "Technology", "region": "Europe", "exchange": "Euronext Amsterdam"},
    "HEIA.AS":   {"name": "Heineken NV", "sector": "Consumer", "region": "Europe", "exchange": "Euronext Amsterdam"},

    # ══════════════════════════════════════════
    #  UK — FTSE 100 (~12)
    # ══════════════════════════════════════════
    "SHEL":      {"name": "Shell plc", "sector": "Energy", "region": "Europe", "exchange": "LSE"},
    "AZN":       {"name": "AstraZeneca plc", "sector": "Healthcare", "region": "Europe", "exchange": "LSE"},
    "HSBA.L":    {"name": "HSBC Holdings plc", "sector": "Finance", "region": "Europe", "exchange": "LSE"},
    "ULVR.L":    {"name": "Unilever plc", "sector": "Consumer", "region": "Europe", "exchange": "LSE"},
    "BP.L":      {"name": "BP plc", "sector": "Energy", "region": "Europe", "exchange": "LSE"},
    "GSK.L":     {"name": "GSK plc", "sector": "Healthcare", "region": "Europe", "exchange": "LSE"},
    "RIO.L":     {"name": "Rio Tinto plc", "sector": "Materials", "region": "Europe", "exchange": "LSE"},
    "LSEG.L":    {"name": "London Stock Exchange Group", "sector": "Finance", "region": "Europe", "exchange": "LSE"},
    "DGE.L":     {"name": "Diageo plc", "sector": "Consumer", "region": "Europe", "exchange": "LSE"},
    "BA.L":      {"name": "BAE Systems plc", "sector": "Industrials", "region": "Europe", "exchange": "LSE"},
    "RR.L":      {"name": "Rolls-Royce Holdings", "sector": "Industrials", "region": "Europe", "exchange": "LSE"},
    "EXPN.L":    {"name": "Experian plc", "sector": "Technology", "region": "Europe", "exchange": "LSE"},

    # ══════════════════════════════════════════
    #  Switzerland — SMI (~6)
    # ══════════════════════════════════════════
    "NESN.SW":   {"name": "Nestle SA", "sector": "Consumer", "region": "Europe", "exchange": "SIX"},
    "ROG.SW":    {"name": "Roche Holding AG", "sector": "Healthcare", "region": "Europe", "exchange": "SIX"},
    "NOVN.SW":   {"name": "Novartis AG", "sector": "Healthcare", "region": "Europe", "exchange": "SIX"},
    "UBSG.SW":   {"name": "UBS Group AG", "sector": "Finance", "region": "Europe", "exchange": "SIX"},
    "ABBN.SW":   {"name": "ABB Ltd", "sector": "Industrials", "region": "Europe", "exchange": "SIX"},
    "ZURN.SW":   {"name": "Zurich Insurance Group", "sector": "Finance", "region": "Europe", "exchange": "SIX"},

    # ══════════════════════════════════════════
    #  Scandinavia — OMX (~6)
    # ══════════════════════════════════════════
    "NOVO-B.CO": {"name": "Novo Nordisk A/S", "sector": "Healthcare", "region": "Europe", "exchange": "OMX Copenhagen"},
    "ERIC-B.ST": {"name": "Ericsson AB", "sector": "Technology", "region": "Europe", "exchange": "OMX Stockholm"},
    "VOLV-B.ST": {"name": "Volvo AB", "sector": "Industrials", "region": "Europe", "exchange": "OMX Stockholm"},
    "SAND.ST":   {"name": "Sandvik AB", "sector": "Industrials", "region": "Europe", "exchange": "OMX Stockholm"},
    "HM-B.ST":   {"name": "H&M AB", "sector": "Consumer", "region": "Europe", "exchange": "OMX Stockholm"},
    "NESTE.HE":  {"name": "Neste Oyj", "sector": "Energy", "region": "Europe", "exchange": "OMX Helsinki"},

    # ══════════════════════════════════════════
    #  Spain & Italy (~8)
    # ══════════════════════════════════════════
    "SAN.MC":    {"name": "Banco Santander SA", "sector": "Finance", "region": "Europe", "exchange": "BME"},
    "ITX.MC":    {"name": "Inditex SA", "sector": "Consumer", "region": "Europe", "exchange": "BME"},
    "IBE.MC":    {"name": "Iberdrola SA", "sector": "Utilities", "region": "Europe", "exchange": "BME"},
    "TEF.MC":    {"name": "Telefonica SA", "sector": "Communication", "region": "Europe", "exchange": "BME"},
    "ISP.MI":    {"name": "Intesa Sanpaolo SpA", "sector": "Finance", "region": "Europe", "exchange": "Borsa Italiana"},
    "ENI.MI":    {"name": "Eni SpA", "sector": "Energy", "region": "Europe", "exchange": "Borsa Italiana"},
    "UCG.MI":    {"name": "UniCredit SpA", "sector": "Finance", "region": "Europe", "exchange": "Borsa Italiana"},
    "ENEL.MI":   {"name": "Enel SpA", "sector": "Utilities", "region": "Europe", "exchange": "Borsa Italiana"},

    # ══════════════════════════════════════════
    #  Belgium (~3)
    # ══════════════════════════════════════════
    "ABI.BR":    {"name": "Anheuser-Busch InBev", "sector": "Consumer", "region": "Europe", "exchange": "Euronext Brussels"},
    "UCB.BR":    {"name": "UCB SA", "sector": "Healthcare", "region": "Europe", "exchange": "Euronext Brussels"},
    "SOLB.BR":   {"name": "Solvay SA", "sector": "Materials", "region": "Europe", "exchange": "Euronext Brussels"},
    # ══════════════════════════════════════════
    #  S&P 500 & NASDAQ 100 Extensions
    # ══════════════════════════════════════════
    "MMM": {"name": "3M", "sector": "Industrials", "region": "US", "exchange": "US"},
    "AOS": {"name": "A. O. Smith", "sector": "Industrials", "region": "US", "exchange": "US"},
    "ABT": {"name": "Abbott Laboratories", "sector": "Health Care", "region": "US", "exchange": "US"},
    "ADBE": {"name": "Adobe Inc.", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "AES": {"name": "AES Corporation", "sector": "Utilities", "region": "US", "exchange": "US"},
    "AFL": {"name": "Aflac", "sector": "Financials", "region": "US", "exchange": "US"},
    "A": {"name": "Agilent Technologies", "sector": "Health Care", "region": "US", "exchange": "US"},
    "APD": {"name": "Air Products", "sector": "Materials", "region": "US", "exchange": "US"},
    "ABNB": {"name": "Airbnb", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "AKAM": {"name": "Akamai Technologies", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "ALB": {"name": "Albemarle Corporation", "sector": "Materials", "region": "US", "exchange": "US"},
    "ARE": {"name": "Alexandria Real Estate Equities", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "ALGN": {"name": "Align Technology", "sector": "Health Care", "region": "US", "exchange": "US"},
    "ALLE": {"name": "Allegion", "sector": "Industrials", "region": "US", "exchange": "US"},
    "LNT": {"name": "Alliant Energy", "sector": "Utilities", "region": "US", "exchange": "US"},
    "ALL": {"name": "Allstate", "sector": "Financials", "region": "US", "exchange": "US"},
    "GOOG": {"name": "Alphabet Inc. (Class C)", "sector": "Communication Services", "region": "US", "exchange": "US"},
    "MO": {"name": "Altria", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "AMCR": {"name": "Amcor", "sector": "Materials", "region": "US", "exchange": "US"},
    "AEE": {"name": "Ameren", "sector": "Utilities", "region": "US", "exchange": "US"},
    "AEP": {"name": "American Electric Power", "sector": "Utilities", "region": "US", "exchange": "US"},
    "AXP": {"name": "American Express", "sector": "Financials", "region": "US", "exchange": "US"},
    "AIG": {"name": "American International Group", "sector": "Financials", "region": "US", "exchange": "US"},
    "AMT": {"name": "American Tower", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "AWK": {"name": "American Water Works", "sector": "Utilities", "region": "US", "exchange": "US"},
    "AMP": {"name": "Ameriprise Financial", "sector": "Financials", "region": "US", "exchange": "US"},
    "AME": {"name": "Ametek", "sector": "Industrials", "region": "US", "exchange": "US"},
    "AMGN": {"name": "Amgen", "sector": "Health Care", "region": "US", "exchange": "US"},
    "APH": {"name": "Amphenol", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "ADI": {"name": "Analog Devices", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "AON": {"name": "Aon plc", "sector": "Financials", "region": "US", "exchange": "US"},
    "APA": {"name": "APA Corporation", "sector": "Energy", "region": "US", "exchange": "US"},
    "APO": {"name": "Apollo Global Management", "sector": "Financials", "region": "US", "exchange": "US"},
    "AMAT": {"name": "Applied Materials", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "APP": {"name": "AppLovin", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "APTV": {"name": "Aptiv", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "ACGL": {"name": "Arch Capital Group", "sector": "Financials", "region": "US", "exchange": "US"},
    "ADM": {"name": "Archer Daniels Midland", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "ARES": {"name": "Ares Management", "sector": "Financials", "region": "US", "exchange": "US"},
    "ANET": {"name": "Arista Networks", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "AJG": {"name": "Arthur J. Gallagher &amp; Co.", "sector": "Financials", "region": "US", "exchange": "US"},
    "AIZ": {"name": "Assurant", "sector": "Financials", "region": "US", "exchange": "US"},
    "T": {"name": "AT&amp;T", "sector": "Communication Services", "region": "US", "exchange": "US"},
    "ATO": {"name": "Atmos Energy", "sector": "Utilities", "region": "US", "exchange": "US"},
    "ADSK": {"name": "Autodesk", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "ADP": {"name": "Automatic Data Processing", "sector": "Industrials", "region": "US", "exchange": "US"},
    "AZO": {"name": "AutoZone", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "AVB": {"name": "AvalonBay Communities", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "AVY": {"name": "Avery Dennison", "sector": "Materials", "region": "US", "exchange": "US"},
    "AXON": {"name": "Axon Enterprise", "sector": "Industrials", "region": "US", "exchange": "US"},
    "BKR": {"name": "Baker Hughes", "sector": "Energy", "region": "US", "exchange": "US"},
    "BALL": {"name": "Ball Corporation", "sector": "Materials", "region": "US", "exchange": "US"},
    "BAX": {"name": "Baxter International", "sector": "Health Care", "region": "US", "exchange": "US"},
    "BDX": {"name": "Becton Dickinson", "sector": "Health Care", "region": "US", "exchange": "US"},
    "BRK-B": {"name": "Berkshire Hathaway", "sector": "Financials", "region": "US", "exchange": "US"},
    "BBY": {"name": "Best Buy", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "TECH": {"name": "Bio-Techne", "sector": "Health Care", "region": "US", "exchange": "US"},
    "BIIB": {"name": "Biogen", "sector": "Health Care", "region": "US", "exchange": "US"},
    "BX": {"name": "Blackstone Inc.", "sector": "Financials", "region": "US", "exchange": "US"},
    "XYZ": {"name": "Block, Inc.", "sector": "Financials", "region": "US", "exchange": "US"},
    "BK": {"name": "BNY Mellon", "sector": "Financials", "region": "US", "exchange": "US"},
    "BKNG": {"name": "Booking Holdings", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "BSX": {"name": "Boston Scientific", "sector": "Health Care", "region": "US", "exchange": "US"},
    "BMY": {"name": "Bristol Myers Squibb", "sector": "Health Care", "region": "US", "exchange": "US"},
    "BR": {"name": "Broadridge Financial Solutions", "sector": "Industrials", "region": "US", "exchange": "US"},
    "BRO": {"name": "Brown &amp; Brown", "sector": "Financials", "region": "US", "exchange": "US"},
    "BF-B": {"name": "Brown–Forman", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "BLDR": {"name": "Builders FirstSource", "sector": "Industrials", "region": "US", "exchange": "US"},
    "BG": {"name": "Bunge Global", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "BXP": {"name": "BXP, Inc.", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "CHRW": {"name": "C.H. Robinson", "sector": "Industrials", "region": "US", "exchange": "US"},
    "CDNS": {"name": "Cadence Design Systems", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "CPT": {"name": "Camden Property Trust", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "CPB": {"name": "Campbell's Company (The)", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "COF": {"name": "Capital One", "sector": "Financials", "region": "US", "exchange": "US"},
    "CAH": {"name": "Cardinal Health", "sector": "Health Care", "region": "US", "exchange": "US"},
    "CCL": {"name": "Carnival", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "CARR": {"name": "Carrier Global", "sector": "Industrials", "region": "US", "exchange": "US"},
    "CVNA": {"name": "Carvana", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "CBOE": {"name": "Cboe Global Markets", "sector": "Financials", "region": "US", "exchange": "US"},
    "CBRE": {"name": "CBRE Group", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "CDW": {"name": "CDW Corporation", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "COR": {"name": "Cencora", "sector": "Health Care", "region": "US", "exchange": "US"},
    "CNC": {"name": "Centene Corporation", "sector": "Health Care", "region": "US", "exchange": "US"},
    "CNP": {"name": "CenterPoint Energy", "sector": "Utilities", "region": "US", "exchange": "US"},
    "CF": {"name": "CF Industries", "sector": "Materials", "region": "US", "exchange": "US"},
    "CRL": {"name": "Charles River Laboratories", "sector": "Health Care", "region": "US", "exchange": "US"},
    "SCHW": {"name": "Charles Schwab Corporation", "sector": "Financials", "region": "US", "exchange": "US"},
    "CHTR": {"name": "Charter Communications", "sector": "Communication Services", "region": "US", "exchange": "US"},
    "CMG": {"name": "Chipotle Mexican Grill", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "CB": {"name": "Chubb Limited", "sector": "Financials", "region": "US", "exchange": "US"},
    "CHD": {"name": "Church &amp; Dwight", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "CIEN": {"name": "Ciena", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "CI": {"name": "Cigna", "sector": "Health Care", "region": "US", "exchange": "US"},
    "CINF": {"name": "Cincinnati Financial", "sector": "Financials", "region": "US", "exchange": "US"},
    "CTAS": {"name": "Cintas", "sector": "Industrials", "region": "US", "exchange": "US"},
    "C": {"name": "Citigroup", "sector": "Financials", "region": "US", "exchange": "US"},
    "CFG": {"name": "Citizens Financial Group", "sector": "Financials", "region": "US", "exchange": "US"},
    "CLX": {"name": "Clorox", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "CME": {"name": "CME Group", "sector": "Financials", "region": "US", "exchange": "US"},
    "CMS": {"name": "CMS Energy", "sector": "Utilities", "region": "US", "exchange": "US"},
    "CTSH": {"name": "Cognizant", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "COIN": {"name": "Coinbase", "sector": "Financials", "region": "US", "exchange": "US"},
    "CL": {"name": "Colgate-Palmolive", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "CMCSA": {"name": "Comcast", "sector": "Communication Services", "region": "US", "exchange": "US"},
    "FIX": {"name": "Comfort Systems USA", "sector": "Industrials", "region": "US", "exchange": "US"},
    "CAG": {"name": "Conagra Brands", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "ED": {"name": "Consolidated Edison", "sector": "Utilities", "region": "US", "exchange": "US"},
    "STZ": {"name": "Constellation Brands", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "CEG": {"name": "Constellation Energy", "sector": "Utilities", "region": "US", "exchange": "US"},
    "COO": {"name": "Cooper Companies (The)", "sector": "Health Care", "region": "US", "exchange": "US"},
    "CPRT": {"name": "Copart", "sector": "Industrials", "region": "US", "exchange": "US"},
    "GLW": {"name": "Corning Inc.", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "CPAY": {"name": "Corpay", "sector": "Financials", "region": "US", "exchange": "US"},
    "CTVA": {"name": "Corteva", "sector": "Materials", "region": "US", "exchange": "US"},
    "CSGP": {"name": "CoStar Group", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "CTRA": {"name": "Coterra", "sector": "Energy", "region": "US", "exchange": "US"},
    "CRH": {"name": "CRH plc", "sector": "Materials", "region": "US", "exchange": "US"},
    "CRWD": {"name": "CrowdStrike", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "CCI": {"name": "Crown Castle", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "CSX": {"name": "CSX Corporation", "sector": "Industrials", "region": "US", "exchange": "US"},
    "CMI": {"name": "Cummins", "sector": "Industrials", "region": "US", "exchange": "US"},
    "CVS": {"name": "CVS Health", "sector": "Health Care", "region": "US", "exchange": "US"},
    "DHR": {"name": "Danaher Corporation", "sector": "Health Care", "region": "US", "exchange": "US"},
    "DRI": {"name": "Darden Restaurants", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "DDOG": {"name": "Datadog", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "DVA": {"name": "DaVita", "sector": "Health Care", "region": "US", "exchange": "US"},
    "DECK": {"name": "Deckers Brands", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "DELL": {"name": "Dell Technologies", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "DAL": {"name": "Delta Air Lines", "sector": "Industrials", "region": "US", "exchange": "US"},
    "DVN": {"name": "Devon Energy", "sector": "Energy", "region": "US", "exchange": "US"},
    "DXCM": {"name": "Dexcom", "sector": "Health Care", "region": "US", "exchange": "US"},
    "FANG": {"name": "Diamondback Energy", "sector": "Energy", "region": "US", "exchange": "US"},
    "DLR": {"name": "Digital Realty", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "DG": {"name": "Dollar General", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "DLTR": {"name": "Dollar Tree", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "D": {"name": "Dominion Energy", "sector": "Utilities", "region": "US", "exchange": "US"},
    "DPZ": {"name": "Domino's", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "DASH": {"name": "DoorDash", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "DOV": {"name": "Dover Corporation", "sector": "Industrials", "region": "US", "exchange": "US"},
    "DOW": {"name": "Dow Inc.", "sector": "Materials", "region": "US", "exchange": "US"},
    "DHI": {"name": "D. R. Horton", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "DTE": {"name": "DTE Energy", "sector": "Utilities", "region": "US", "exchange": "US"},
    "DUK": {"name": "Duke Energy", "sector": "Utilities", "region": "US", "exchange": "US"},
    "DD": {"name": "DuPont", "sector": "Materials", "region": "US", "exchange": "US"},
    "ETN": {"name": "Eaton Corporation", "sector": "Industrials", "region": "US", "exchange": "US"},
    "EBAY": {"name": "eBay Inc.", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "ECL": {"name": "Ecolab", "sector": "Materials", "region": "US", "exchange": "US"},
    "EIX": {"name": "Edison International", "sector": "Utilities", "region": "US", "exchange": "US"},
    "EW": {"name": "Edwards Lifesciences", "sector": "Health Care", "region": "US", "exchange": "US"},
    "EA": {"name": "Electronic Arts", "sector": "Communication Services", "region": "US", "exchange": "US"},
    "ELV": {"name": "Elevance Health", "sector": "Health Care", "region": "US", "exchange": "US"},
    "EME": {"name": "Emcor", "sector": "Industrials", "region": "US", "exchange": "US"},
    "EMR": {"name": "Emerson Electric", "sector": "Industrials", "region": "US", "exchange": "US"},
    "ETR": {"name": "Entergy", "sector": "Utilities", "region": "US", "exchange": "US"},
    "EOG": {"name": "EOG Resources", "sector": "Energy", "region": "US", "exchange": "US"},
    "EPAM": {"name": "EPAM Systems", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "EQT": {"name": "EQT Corporation", "sector": "Energy", "region": "US", "exchange": "US"},
    "EFX": {"name": "Equifax", "sector": "Industrials", "region": "US", "exchange": "US"},
    "EQIX": {"name": "Equinix", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "EQR": {"name": "Equity Residential", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "ERIE": {"name": "Erie Indemnity", "sector": "Financials", "region": "US", "exchange": "US"},
    "ESS": {"name": "Essex Property Trust", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "EL": {"name": "Estée Lauder Companies (The)", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "EG": {"name": "Everest Group", "sector": "Financials", "region": "US", "exchange": "US"},
    "EVRG": {"name": "Evergy", "sector": "Utilities", "region": "US", "exchange": "US"},
    "ES": {"name": "Eversource Energy", "sector": "Utilities", "region": "US", "exchange": "US"},
    "EXC": {"name": "Exelon", "sector": "Utilities", "region": "US", "exchange": "US"},
    "EXE": {"name": "Expand Energy", "sector": "Energy", "region": "US", "exchange": "US"},
    "EXPE": {"name": "Expedia Group", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "EXPD": {"name": "Expeditors International", "sector": "Industrials", "region": "US", "exchange": "US"},
    "EXR": {"name": "Extra Space Storage", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "FFIV": {"name": "F5, Inc.", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "FDS": {"name": "FactSet", "sector": "Financials", "region": "US", "exchange": "US"},
    "FICO": {"name": "Fair Isaac", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "FAST": {"name": "Fastenal", "sector": "Industrials", "region": "US", "exchange": "US"},
    "FRT": {"name": "Federal Realty Investment Trust", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "FDX": {"name": "FedEx", "sector": "Industrials", "region": "US", "exchange": "US"},
    "FIS": {"name": "Fidelity National Information Services", "sector": "Financials", "region": "US", "exchange": "US"},
    "FITB": {"name": "Fifth Third Bancorp", "sector": "Financials", "region": "US", "exchange": "US"},
    "FSLR": {"name": "First Solar", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "FE": {"name": "FirstEnergy", "sector": "Utilities", "region": "US", "exchange": "US"},
    "FISV": {"name": "Fiserv", "sector": "Financials", "region": "US", "exchange": "US"},
    "F": {"name": "Ford Motor Company", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "FTNT": {"name": "Fortinet", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "FTV": {"name": "Fortive", "sector": "Industrials", "region": "US", "exchange": "US"},
    "FOXA": {"name": "Fox Corporation (Class A)", "sector": "Communication Services", "region": "US", "exchange": "US"},
    "FOX": {"name": "Fox Corporation (Class B)", "sector": "Communication Services", "region": "US", "exchange": "US"},
    "BEN": {"name": "Franklin Resources", "sector": "Financials", "region": "US", "exchange": "US"},
    "FCX": {"name": "Freeport-McMoRan", "sector": "Materials", "region": "US", "exchange": "US"},
    "GRMN": {"name": "Garmin", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "IT": {"name": "Gartner", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "GEHC": {"name": "GE HealthCare", "sector": "Health Care", "region": "US", "exchange": "US"},
    "GEV": {"name": "GE Vernova", "sector": "Industrials", "region": "US", "exchange": "US"},
    "GEN": {"name": "Gen Digital", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "GNRC": {"name": "Generac", "sector": "Industrials", "region": "US", "exchange": "US"},
    "GD": {"name": "General Dynamics", "sector": "Industrials", "region": "US", "exchange": "US"},
    "GIS": {"name": "General Mills", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "GM": {"name": "General Motors", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "GPC": {"name": "Genuine Parts Company", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "GILD": {"name": "Gilead Sciences", "sector": "Health Care", "region": "US", "exchange": "US"},
    "GPN": {"name": "Global Payments", "sector": "Financials", "region": "US", "exchange": "US"},
    "GL": {"name": "Globe Life", "sector": "Financials", "region": "US", "exchange": "US"},
    "GDDY": {"name": "GoDaddy", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "HAL": {"name": "Halliburton", "sector": "Energy", "region": "US", "exchange": "US"},
    "HIG": {"name": "Hartford (The)", "sector": "Financials", "region": "US", "exchange": "US"},
    "HAS": {"name": "Hasbro", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "HCA": {"name": "HCA Healthcare", "sector": "Health Care", "region": "US", "exchange": "US"},
    "DOC": {"name": "Healthpeak Properties", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "HSIC": {"name": "Henry Schein", "sector": "Health Care", "region": "US", "exchange": "US"},
    "HSY": {"name": "Hershey Company (The)", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "HPE": {"name": "Hewlett Packard Enterprise", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "HLT": {"name": "Hilton Worldwide", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "HOLX": {"name": "Hologic", "sector": "Health Care", "region": "US", "exchange": "US"},
    "HON": {"name": "Honeywell", "sector": "Industrials", "region": "US", "exchange": "US"},
    "HRL": {"name": "Hormel Foods", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "HST": {"name": "Host Hotels &amp; Resorts", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "HWM": {"name": "Howmet Aerospace", "sector": "Industrials", "region": "US", "exchange": "US"},
    "HPQ": {"name": "HP Inc.", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "HUBB": {"name": "Hubbell Incorporated", "sector": "Industrials", "region": "US", "exchange": "US"},
    "HUM": {"name": "Humana", "sector": "Health Care", "region": "US", "exchange": "US"},
    "HBAN": {"name": "Huntington Bancshares", "sector": "Financials", "region": "US", "exchange": "US"},
    "HII": {"name": "Huntington Ingalls Industries", "sector": "Industrials", "region": "US", "exchange": "US"},
    "IEX": {"name": "IDEX Corporation", "sector": "Industrials", "region": "US", "exchange": "US"},
    "IDXX": {"name": "Idexx Laboratories", "sector": "Health Care", "region": "US", "exchange": "US"},
    "ITW": {"name": "Illinois Tool Works", "sector": "Industrials", "region": "US", "exchange": "US"},
    "INCY": {"name": "Incyte", "sector": "Health Care", "region": "US", "exchange": "US"},
    "IR": {"name": "Ingersoll Rand", "sector": "Industrials", "region": "US", "exchange": "US"},
    "PODD": {"name": "Insulet Corporation", "sector": "Health Care", "region": "US", "exchange": "US"},
    "IBKR": {"name": "Interactive Brokers", "sector": "Financials", "region": "US", "exchange": "US"},
    "ICE": {"name": "Intercontinental Exchange", "sector": "Financials", "region": "US", "exchange": "US"},
    "IFF": {"name": "International Flavors &amp; Fragrances", "sector": "Materials", "region": "US", "exchange": "US"},
    "IP": {"name": "International Paper", "sector": "Materials", "region": "US", "exchange": "US"},
    "INTU": {"name": "Intuit", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "ISRG": {"name": "Intuitive Surgical", "sector": "Health Care", "region": "US", "exchange": "US"},
    "IVZ": {"name": "Invesco", "sector": "Financials", "region": "US", "exchange": "US"},
    "INVH": {"name": "Invitation Homes", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "IQV": {"name": "IQVIA", "sector": "Health Care", "region": "US", "exchange": "US"},
    "IRM": {"name": "Iron Mountain", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "JBHT": {"name": "J.B. Hunt", "sector": "Industrials", "region": "US", "exchange": "US"},
    "JBL": {"name": "Jabil", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "JKHY": {"name": "Jack Henry &amp; Associates", "sector": "Financials", "region": "US", "exchange": "US"},
    "J": {"name": "Jacobs Solutions", "sector": "Industrials", "region": "US", "exchange": "US"},
    "JCI": {"name": "Johnson Controls", "sector": "Industrials", "region": "US", "exchange": "US"},
    "KVUE": {"name": "Kenvue", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "KDP": {"name": "Keurig Dr Pepper", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "KEY": {"name": "KeyCorp", "sector": "Financials", "region": "US", "exchange": "US"},
    "KEYS": {"name": "Keysight Technologies", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "KMB": {"name": "Kimberly-Clark", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "KIM": {"name": "Kimco Realty", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "KMI": {"name": "Kinder Morgan", "sector": "Energy", "region": "US", "exchange": "US"},
    "KKR": {"name": "KKR &amp; Co.", "sector": "Financials", "region": "US", "exchange": "US"},
    "KLAC": {"name": "KLA Corporation", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "KHC": {"name": "Kraft Heinz", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "KR": {"name": "Kroger", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "LHX": {"name": "L3Harris", "sector": "Industrials", "region": "US", "exchange": "US"},
    "LH": {"name": "Labcorp", "sector": "Health Care", "region": "US", "exchange": "US"},
    "LRCX": {"name": "Lam Research", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "LW": {"name": "Lamb Weston", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "LVS": {"name": "Las Vegas Sands", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "LDOS": {"name": "Leidos", "sector": "Industrials", "region": "US", "exchange": "US"},
    "LEN": {"name": "Lennar", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "LII": {"name": "Lennox International", "sector": "Industrials", "region": "US", "exchange": "US"},
    "LYV": {"name": "Live Nation Entertainment", "sector": "Communication Services", "region": "US", "exchange": "US"},
    "LMT": {"name": "Lockheed Martin", "sector": "Industrials", "region": "US", "exchange": "US"},
    "L": {"name": "Loews Corporation", "sector": "Financials", "region": "US", "exchange": "US"},
    "LOW": {"name": "Lowe's", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "LULU": {"name": "Lululemon Athletica", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "LYB": {"name": "LyondellBasell", "sector": "Materials", "region": "US", "exchange": "US"},
    "MTB": {"name": "M&amp;T Bank", "sector": "Financials", "region": "US", "exchange": "US"},
    "MPC": {"name": "Marathon Petroleum", "sector": "Energy", "region": "US", "exchange": "US"},
    "MAR": {"name": "Marriott International", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "MRSH": {"name": "Marsh McLennan", "sector": "Financials", "region": "US", "exchange": "US"},
    "MLM": {"name": "Martin Marietta Materials", "sector": "Materials", "region": "US", "exchange": "US"},
    "MAS": {"name": "Masco", "sector": "Industrials", "region": "US", "exchange": "US"},
    "MTCH": {"name": "Match Group", "sector": "Communication Services", "region": "US", "exchange": "US"},
    "MKC": {"name": "McCormick &amp; Company", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "MCD": {"name": "McDonald's", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "MCK": {"name": "McKesson Corporation", "sector": "Health Care", "region": "US", "exchange": "US"},
    "MDT": {"name": "Medtronic", "sector": "Health Care", "region": "US", "exchange": "US"},
    "MET": {"name": "MetLife", "sector": "Financials", "region": "US", "exchange": "US"},
    "MTD": {"name": "Mettler Toledo", "sector": "Health Care", "region": "US", "exchange": "US"},
    "MGM": {"name": "MGM Resorts", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "MCHP": {"name": "Microchip Technology", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "MU": {"name": "Micron Technology", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "MAA": {"name": "Mid-America Apartment Communities", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "MRNA": {"name": "Moderna", "sector": "Health Care", "region": "US", "exchange": "US"},
    "MOH": {"name": "Molina Healthcare", "sector": "Health Care", "region": "US", "exchange": "US"},
    "TAP": {"name": "Molson Coors Beverage Company", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "MDLZ": {"name": "Mondelez International", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "MPWR": {"name": "Monolithic Power Systems", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "MNST": {"name": "Monster Beverage", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "MCO": {"name": "Moody's Corporation", "sector": "Financials", "region": "US", "exchange": "US"},
    "MOS": {"name": "Mosaic Company (The)", "sector": "Materials", "region": "US", "exchange": "US"},
    "MSI": {"name": "Motorola Solutions", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "MSCI": {"name": "MSCI Inc.", "sector": "Financials", "region": "US", "exchange": "US"},
    "NDAQ": {"name": "Nasdaq, Inc.", "sector": "Financials", "region": "US", "exchange": "US"},
    "NTAP": {"name": "NetApp", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "NEM": {"name": "Newmont", "sector": "Materials", "region": "US", "exchange": "US"},
    "NWSA": {"name": "News Corp (Class A)", "sector": "Communication Services", "region": "US", "exchange": "US"},
    "NWS": {"name": "News Corp (Class B)", "sector": "Communication Services", "region": "US", "exchange": "US"},
    "NKE": {"name": "Nike, Inc.", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "NI": {"name": "NiSource", "sector": "Utilities", "region": "US", "exchange": "US"},
    "NDSN": {"name": "Nordson Corporation", "sector": "Industrials", "region": "US", "exchange": "US"},
    "NSC": {"name": "Norfolk Southern", "sector": "Industrials", "region": "US", "exchange": "US"},
    "NTRS": {"name": "Northern Trust", "sector": "Financials", "region": "US", "exchange": "US"},
    "NOC": {"name": "Northrop Grumman", "sector": "Industrials", "region": "US", "exchange": "US"},
    "NCLH": {"name": "Norwegian Cruise Line Holdings", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "NRG": {"name": "NRG Energy", "sector": "Utilities", "region": "US", "exchange": "US"},
    "NUE": {"name": "Nucor", "sector": "Materials", "region": "US", "exchange": "US"},
    "NVR": {"name": "NVR, Inc.", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "NXPI": {"name": "NXP Semiconductors", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "ORLY": {"name": "O’Reilly Automotive", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "OXY": {"name": "Occidental Petroleum", "sector": "Energy", "region": "US", "exchange": "US"},
    "ODFL": {"name": "Old Dominion", "sector": "Industrials", "region": "US", "exchange": "US"},
    "OMC": {"name": "Omnicom Group", "sector": "Communication Services", "region": "US", "exchange": "US"},
    "ON": {"name": "ON Semiconductor", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "OKE": {"name": "Oneok", "sector": "Energy", "region": "US", "exchange": "US"},
    "OTIS": {"name": "Otis Worldwide", "sector": "Industrials", "region": "US", "exchange": "US"},
    "PCAR": {"name": "Paccar", "sector": "Industrials", "region": "US", "exchange": "US"},
    "PKG": {"name": "Packaging Corporation of America", "sector": "Materials", "region": "US", "exchange": "US"},
    "PLTR": {"name": "Palantir Technologies", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "PSKY": {"name": "Paramount Skydance Corporation", "sector": "Communication Services", "region": "US", "exchange": "US"},
    "PH": {"name": "Parker Hannifin", "sector": "Industrials", "region": "US", "exchange": "US"},
    "PAYX": {"name": "Paychex", "sector": "Industrials", "region": "US", "exchange": "US"},
    "PAYC": {"name": "Paycom", "sector": "Industrials", "region": "US", "exchange": "US"},
    "PNR": {"name": "Pentair", "sector": "Industrials", "region": "US", "exchange": "US"},
    "PCG": {"name": "PG&amp;E Corporation", "sector": "Utilities", "region": "US", "exchange": "US"},
    "PM": {"name": "Philip Morris International", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "PSX": {"name": "Phillips 66", "sector": "Energy", "region": "US", "exchange": "US"},
    "PNW": {"name": "Pinnacle West Capital", "sector": "Utilities", "region": "US", "exchange": "US"},
    "PNC": {"name": "PNC Financial Services", "sector": "Financials", "region": "US", "exchange": "US"},
    "POOL": {"name": "Pool Corporation", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "PPG": {"name": "PPG Industries", "sector": "Materials", "region": "US", "exchange": "US"},
    "PPL": {"name": "PPL Corporation", "sector": "Utilities", "region": "US", "exchange": "US"},
    "PFG": {"name": "Principal Financial Group", "sector": "Financials", "region": "US", "exchange": "US"},
    "PGR": {"name": "Progressive Corporation", "sector": "Financials", "region": "US", "exchange": "US"},
    "PLD": {"name": "Prologis", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "PRU": {"name": "Prudential Financial", "sector": "Financials", "region": "US", "exchange": "US"},
    "PEG": {"name": "Public Service Enterprise Group", "sector": "Utilities", "region": "US", "exchange": "US"},
    "PTC": {"name": "PTC Inc.", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "PSA": {"name": "Public Storage", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "PHM": {"name": "PulteGroup", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "PWR": {"name": "Quanta Services", "sector": "Industrials", "region": "US", "exchange": "US"},
    "DGX": {"name": "Quest Diagnostics", "sector": "Health Care", "region": "US", "exchange": "US"},
    "Q": {"name": "Qnity Electronics", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "RL": {"name": "Ralph Lauren Corporation", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "RJF": {"name": "Raymond James Financial", "sector": "Financials", "region": "US", "exchange": "US"},
    "RTX": {"name": "RTX Corporation", "sector": "Industrials", "region": "US", "exchange": "US"},
    "O": {"name": "Realty Income", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "REG": {"name": "Regency Centers", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "REGN": {"name": "Regeneron Pharmaceuticals", "sector": "Health Care", "region": "US", "exchange": "US"},
    "RF": {"name": "Regions Financial Corporation", "sector": "Financials", "region": "US", "exchange": "US"},
    "RSG": {"name": "Republic Services", "sector": "Industrials", "region": "US", "exchange": "US"},
    "RMD": {"name": "ResMed", "sector": "Health Care", "region": "US", "exchange": "US"},
    "RVTY": {"name": "Revvity", "sector": "Health Care", "region": "US", "exchange": "US"},
    "HOOD": {"name": "Robinhood Markets", "sector": "Financials", "region": "US", "exchange": "US"},
    "ROK": {"name": "Rockwell Automation", "sector": "Industrials", "region": "US", "exchange": "US"},
    "ROL": {"name": "Rollins, Inc.", "sector": "Industrials", "region": "US", "exchange": "US"},
    "ROP": {"name": "Roper Technologies", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "ROST": {"name": "Ross Stores", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "RCL": {"name": "Royal Caribbean Group", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "SPGI": {"name": "S&amp;P Global", "sector": "Financials", "region": "US", "exchange": "US"},
    "SNDK": {"name": "Sandisk", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "SBAC": {"name": "SBA Communications", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "SLB": {"name": "Schlumberger", "sector": "Energy", "region": "US", "exchange": "US"},
    "STX": {"name": "Seagate Technology", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "SRE": {"name": "Sempra", "sector": "Utilities", "region": "US", "exchange": "US"},
    "SHW": {"name": "Sherwin-Williams", "sector": "Materials", "region": "US", "exchange": "US"},
    "SPG": {"name": "Simon Property Group", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "SWKS": {"name": "Skyworks Solutions", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "SJM": {"name": "J.M. Smucker Company (The)", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "SW": {"name": "Smurfit Westrock", "sector": "Materials", "region": "US", "exchange": "US"},
    "SNA": {"name": "Snap-on", "sector": "Industrials", "region": "US", "exchange": "US"},
    "SOLV": {"name": "Solventum", "sector": "Health Care", "region": "US", "exchange": "US"},
    "SO": {"name": "Southern Company", "sector": "Utilities", "region": "US", "exchange": "US"},
    "LUV": {"name": "Southwest Airlines", "sector": "Industrials", "region": "US", "exchange": "US"},
    "SWK": {"name": "Stanley Black &amp; Decker", "sector": "Industrials", "region": "US", "exchange": "US"},
    "SBUX": {"name": "Starbucks", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "STT": {"name": "State Street Corporation", "sector": "Financials", "region": "US", "exchange": "US"},
    "STLD": {"name": "Steel Dynamics", "sector": "Materials", "region": "US", "exchange": "US"},
    "STE": {"name": "Steris", "sector": "Health Care", "region": "US", "exchange": "US"},
    "SYK": {"name": "Stryker Corporation", "sector": "Health Care", "region": "US", "exchange": "US"},
    "SMCI": {"name": "Supermicro", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "SYF": {"name": "Synchrony Financial", "sector": "Financials", "region": "US", "exchange": "US"},
    "SNPS": {"name": "Synopsys", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "SYY": {"name": "Sysco", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "TMUS": {"name": "T-Mobile US", "sector": "Communication Services", "region": "US", "exchange": "US"},
    "TROW": {"name": "T. Rowe Price", "sector": "Financials", "region": "US", "exchange": "US"},
    "TTWO": {"name": "Take-Two Interactive", "sector": "Communication Services", "region": "US", "exchange": "US"},
    "TPR": {"name": "Tapestry, Inc.", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "TRGP": {"name": "Targa Resources", "sector": "Energy", "region": "US", "exchange": "US"},
    "TGT": {"name": "Target Corporation", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "TEL": {"name": "TE Connectivity", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "TDY": {"name": "Teledyne Technologies", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "TER": {"name": "Teradyne", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "TXN": {"name": "Texas Instruments", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "TPL": {"name": "Texas Pacific Land Corporation", "sector": "Energy", "region": "US", "exchange": "US"},
    "TXT": {"name": "Textron", "sector": "Industrials", "region": "US", "exchange": "US"},
    "TJX": {"name": "TJX Companies", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "TKO": {"name": "TKO Group Holdings", "sector": "Communication Services", "region": "US", "exchange": "US"},
    "TTD": {"name": "Trade Desk (The)", "sector": "Communication Services", "region": "US", "exchange": "US"},
    "TSCO": {"name": "Tractor Supply", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "TT": {"name": "Trane Technologies", "sector": "Industrials", "region": "US", "exchange": "US"},
    "TDG": {"name": "TransDigm Group", "sector": "Industrials", "region": "US", "exchange": "US"},
    "TRV": {"name": "Travelers Companies (The)", "sector": "Financials", "region": "US", "exchange": "US"},
    "TRMB": {"name": "Trimble Inc.", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "TFC": {"name": "Truist Financial", "sector": "Financials", "region": "US", "exchange": "US"},
    "TYL": {"name": "Tyler Technologies", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "TSN": {"name": "Tyson Foods", "sector": "Consumer Staples", "region": "US", "exchange": "US"},
    "USB": {"name": "U.S. Bancorp", "sector": "Financials", "region": "US", "exchange": "US"},
    "UBER": {"name": "Uber", "sector": "Industrials", "region": "US", "exchange": "US"},
    "UDR": {"name": "UDR, Inc.", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "ULTA": {"name": "Ulta Beauty", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "UNP": {"name": "Union Pacific Corporation", "sector": "Industrials", "region": "US", "exchange": "US"},
    "UAL": {"name": "United Airlines Holdings", "sector": "Industrials", "region": "US", "exchange": "US"},
    "UPS": {"name": "United Parcel Service", "sector": "Industrials", "region": "US", "exchange": "US"},
    "URI": {"name": "United Rentals", "sector": "Industrials", "region": "US", "exchange": "US"},
    "UHS": {"name": "Universal Health Services", "sector": "Health Care", "region": "US", "exchange": "US"},
    "VLO": {"name": "Valero Energy", "sector": "Energy", "region": "US", "exchange": "US"},
    "VTR": {"name": "Ventas", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "VLTO": {"name": "Veralto", "sector": "Industrials", "region": "US", "exchange": "US"},
    "VRSN": {"name": "Verisign", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "VRSK": {"name": "Verisk Analytics", "sector": "Industrials", "region": "US", "exchange": "US"},
    "VZ": {"name": "Verizon", "sector": "Communication Services", "region": "US", "exchange": "US"},
    "VRTX": {"name": "Vertex Pharmaceuticals", "sector": "Health Care", "region": "US", "exchange": "US"},
    "VTRS": {"name": "Viatris", "sector": "Health Care", "region": "US", "exchange": "US"},
    "VICI": {"name": "Vici Properties", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "VST": {"name": "Vistra Corp.", "sector": "Utilities", "region": "US", "exchange": "US"},
    "VMC": {"name": "Vulcan Materials Company", "sector": "Materials", "region": "US", "exchange": "US"},
    "WRB": {"name": "W. R. Berkley Corporation", "sector": "Financials", "region": "US", "exchange": "US"},
    "GWW": {"name": "W. W. Grainger", "sector": "Industrials", "region": "US", "exchange": "US"},
    "WAB": {"name": "Wabtec", "sector": "Industrials", "region": "US", "exchange": "US"},
    "WBD": {"name": "Warner Bros. Discovery", "sector": "Communication Services", "region": "US", "exchange": "US"},
    "WM": {"name": "Waste Management", "sector": "Industrials", "region": "US", "exchange": "US"},
    "WAT": {"name": "Waters Corporation", "sector": "Health Care", "region": "US", "exchange": "US"},
    "WEC": {"name": "WEC Energy Group", "sector": "Utilities", "region": "US", "exchange": "US"},
    "WFC": {"name": "Wells Fargo", "sector": "Financials", "region": "US", "exchange": "US"},
    "WELL": {"name": "Welltower", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "WST": {"name": "West Pharmaceutical Services", "sector": "Health Care", "region": "US", "exchange": "US"},
    "WDC": {"name": "Western Digital", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "WY": {"name": "Weyerhaeuser", "sector": "Real Estate", "region": "US", "exchange": "US"},
    "WSM": {"name": "Williams-Sonoma, Inc.", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "WMB": {"name": "Williams Companies", "sector": "Energy", "region": "US", "exchange": "US"},
    "WTW": {"name": "Willis Towers Watson", "sector": "Financials", "region": "US", "exchange": "US"},
    "WDAY": {"name": "Workday, Inc.", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "WYNN": {"name": "Wynn Resorts", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "XEL": {"name": "Xcel Energy", "sector": "Utilities", "region": "US", "exchange": "US"},
    "XYL": {"name": "Xylem Inc.", "sector": "Industrials", "region": "US", "exchange": "US"},
    "YUM": {"name": "Yum! Brands", "sector": "Consumer Discretionary", "region": "US", "exchange": "US"},
    "ZBRA": {"name": "Zebra Technologies", "sector": "Information Technology", "region": "US", "exchange": "US"},
    "ZBH": {"name": "Zimmer Biomet", "sector": "Health Care", "region": "US", "exchange": "US"},
    "ZTS": {"name": "Zoetis", "sector": "Health Care", "region": "US", "exchange": "US"},
    "ADBE": {"name": "Adobe Inc-", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "AMD": {"name": "Advanced Micro Devices", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "ABNB": {"name": "Airbnb", "sector": "Consumer Discretionary", "region": "US", "exchange": "NASDAQ"},
    "ALNY": {"name": "Alnylam Pharmaceuticals", "sector": "Health Care", "region": "US", "exchange": "NASDAQ"},
    "GOOGL": {"name": "Alphabet Inc- (Class A)", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "GOOG": {"name": "Alphabet Inc- (Class C)", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "AMZN": {"name": "Amazon", "sector": "Consumer Discretionary", "region": "US", "exchange": "NASDAQ"},
    "AEP": {"name": "American Electric Power", "sector": "Utilities", "region": "US", "exchange": "NASDAQ"},
    "AMGN": {"name": "Amgen", "sector": "Health Care", "region": "US", "exchange": "NASDAQ"},
    "ADI": {"name": "Analog Devices", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "AAPL": {"name": "Apple Inc-", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "AMAT": {"name": "Applied Materials", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "APP": {"name": "AppLovin", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "ARM": {"name": "Arm Holdings", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "ASML": {"name": "ASML Holding", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "TEAM": {"name": "Atlassian", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "ADSK": {"name": "Autodesk", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "ADP": {"name": "Automatic Data Processing", "sector": "Industrials", "region": "US", "exchange": "NASDAQ"},
    "AXON": {"name": "Axon Enterprise", "sector": "Industrials", "region": "US", "exchange": "NASDAQ"},
    "BKR": {"name": "Baker Hughes", "sector": "Energy", "region": "US", "exchange": "NASDAQ"},
    "BKNG": {"name": "Booking Holdings", "sector": "Consumer Discretionary", "region": "US", "exchange": "NASDAQ"},
    "AVGO": {"name": "Broadcom", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "CDNS": {"name": "Cadence Design Systems", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "CHTR": {"name": "Charter Communications", "sector": "Telecommunications", "region": "US", "exchange": "NASDAQ"},
    "CTAS": {"name": "Cintas", "sector": "Industrials", "region": "US", "exchange": "NASDAQ"},
    "CSCO": {"name": "Cisco", "sector": "Telecommunications", "region": "US", "exchange": "NASDAQ"},
    "CCEP": {"name": "Coca-Cola Europacific Partners", "sector": "Consumer Staples", "region": "US", "exchange": "NASDAQ"},
    "CTSH": {"name": "Cognizant", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "CMCSA": {"name": "Comcast", "sector": "Telecommunications", "region": "US", "exchange": "NASDAQ"},
    "CEG": {"name": "Constellation Energy", "sector": "Utilities", "region": "US", "exchange": "NASDAQ"},
    "CPRT": {"name": "Copart", "sector": "Consumer Discretionary", "region": "US", "exchange": "NASDAQ"},
    "CSGP": {"name": "CoStar Group", "sector": "Real Estate", "region": "US", "exchange": "NASDAQ"},
    "COST": {"name": "Costco", "sector": "Consumer Discretionary", "region": "US", "exchange": "NASDAQ"},
    "CRWD": {"name": "CrowdStrike", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "CSX": {"name": "CSX Corporation", "sector": "Industrials", "region": "US", "exchange": "NASDAQ"},
    "DDOG": {"name": "Datadog", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "DXCM": {"name": "DexCom", "sector": "Health Care", "region": "US", "exchange": "NASDAQ"},
    "FANG": {"name": "Diamondback Energy", "sector": "Energy", "region": "US", "exchange": "NASDAQ"},
    "DASH": {"name": "DoorDash", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "EA": {"name": "Electronic Arts", "sector": "Consumer Discretionary", "region": "US", "exchange": "NASDAQ"},
    "EXC": {"name": "Exelon", "sector": "Utilities", "region": "US", "exchange": "NASDAQ"},
    "FAST": {"name": "Fastenal", "sector": "Industrials", "region": "US", "exchange": "NASDAQ"},
    "FER": {"name": "Ferrovial", "sector": "Industrials", "region": "US", "exchange": "NASDAQ"},
    "FTNT": {"name": "Fortinet", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "GEHC": {"name": "GE HealthCare", "sector": "Health Care", "region": "US", "exchange": "NASDAQ"},
    "GILD": {"name": "Gilead Sciences", "sector": "Health Care", "region": "US", "exchange": "NASDAQ"},
    "HON": {"name": "Honeywell", "sector": "Industrials", "region": "US", "exchange": "NASDAQ"},
    "IDXX": {"name": "Idexx Laboratories", "sector": "Health Care", "region": "US", "exchange": "NASDAQ"},
    "INSM": {"name": "Insmed Incorporated", "sector": "Health Care", "region": "US", "exchange": "NASDAQ"},
    "INTC": {"name": "Intel", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "INTU": {"name": "Intuit", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "ISRG": {"name": "Intuitive Surgical", "sector": "Health Care", "region": "US", "exchange": "NASDAQ"},
    "KDP": {"name": "Keurig Dr Pepper", "sector": "Consumer Staples", "region": "US", "exchange": "NASDAQ"},
    "KLAC": {"name": "KLA Corporation", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "KHC": {"name": "Kraft Heinz", "sector": "Consumer Staples", "region": "US", "exchange": "NASDAQ"},
    "LRCX": {"name": "Lam Research", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "LIN": {"name": "Linde plc", "sector": "Basic Materials", "region": "US", "exchange": "NASDAQ"},
    "MAR": {"name": "Marriott International", "sector": "Consumer Discretionary", "region": "US", "exchange": "NASDAQ"},
    "MRVL": {"name": "Marvell Technology", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "MELI": {"name": "Mercado Libre", "sector": "Consumer Discretionary", "region": "US", "exchange": "NASDAQ"},
    "META": {"name": "Meta Platforms", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "MCHP": {"name": "Microchip Technology", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "MU": {"name": "Micron Technology", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "MSFT": {"name": "Microsoft", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "MSTR": {"name": "MicroStrategy", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "MDLZ": {"name": "Mondelez International", "sector": "Consumer Staples", "region": "US", "exchange": "NASDAQ"},
    "MPWR": {"name": "Monolithic Power Systems", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "MNST": {"name": "Monster Beverage", "sector": "Consumer Staples", "region": "US", "exchange": "NASDAQ"},
    "NFLX": {"name": "Netflix, Inc-", "sector": "Consumer Discretionary", "region": "US", "exchange": "NASDAQ"},
    "NVDA": {"name": "Nvidia", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "NXPI": {"name": "NXP Semiconductors", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "ORLY": {"name": "O'Reilly Automotive", "sector": "Consumer Discretionary", "region": "US", "exchange": "NASDAQ"},
    "ODFL": {"name": "Old Dominion Freight Line", "sector": "Industrials", "region": "US", "exchange": "NASDAQ"},
    "PCAR": {"name": "Paccar", "sector": "Consumer Discretionary", "region": "US", "exchange": "NASDAQ"},
    "PLTR": {"name": "Palantir Technologies", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "PANW": {"name": "Palo Alto Networks", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "PAYX": {"name": "Paychex", "sector": "Industrials", "region": "US", "exchange": "NASDAQ"},
    "PYPL": {"name": "PayPal", "sector": "Industrials", "region": "US", "exchange": "NASDAQ"},
    "PDD": {"name": "PDD Holdings", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "PEP": {"name": "PepsiCo", "sector": "Consumer Staples", "region": "US", "exchange": "NASDAQ"},
    "QCOM": {"name": "Qualcomm", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "REGN": {"name": "Regeneron Pharmaceuticals", "sector": "Health Care", "region": "US", "exchange": "NASDAQ"},
    "ROP": {"name": "Roper Technologies", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "ROST": {"name": "Ross Stores", "sector": "Consumer Discretionary", "region": "US", "exchange": "NASDAQ"},
    "STX": {"name": "Seagate Technology", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "SHOP": {"name": "Shopify", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "SBUX": {"name": "Starbucks", "sector": "Consumer Discretionary", "region": "US", "exchange": "NASDAQ"},
    "SNPS": {"name": "Synopsys", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "TMUS": {"name": "T-Mobile US", "sector": "Telecommunications", "region": "US", "exchange": "NASDAQ"},
    "TTWO": {"name": "Take-Two Interactive", "sector": "Consumer Discretionary", "region": "US", "exchange": "NASDAQ"},
    "TSLA": {"name": "Tesla, Inc-", "sector": "Consumer Discretionary", "region": "US", "exchange": "NASDAQ"},
    "TXN": {"name": "Texas Instruments", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "TRI": {"name": "Thomson Reuters", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "VRSK": {"name": "Verisk Analytics", "sector": "Industrials", "region": "US", "exchange": "NASDAQ"},
    "VRTX": {"name": "Vertex Pharmaceuticals", "sector": "Health Care", "region": "US", "exchange": "NASDAQ"},
    "WMT": {"name": "Walmart", "sector": "Consumer Discretionary", "region": "US", "exchange": "NASDAQ"},
    "WBD": {"name": "Warner Bros- Discovery", "sector": "Consumer Discretionary", "region": "US", "exchange": "NASDAQ"},
    "WDC": {"name": "Western Digital", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "WDAY": {"name": "Workday, Inc-", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    "XEL": {"name": "Xcel Energy", "sector": "Utilities", "region": "US", "exchange": "NASDAQ"},
    "ZS": {"name": "Zscaler", "sector": "Technology", "region": "US", "exchange": "NASDAQ"},
    # ══════════════════════════════════════════
    #  Euro Stoxx 50 Extensions
    # ══════════════════════════════════════════
    "ADYEN.AS": {"name": "Adyen", "sector": "Naamloze vennootschap", "region": "Europe", "exchange": "Euro Stoxx 50"},
    "ARGX.BR": {"name": "Argenx", "sector": "Naamloze vennootschap", "region": "Europe", "exchange": "Euro Stoxx 50"},
    "ASML.AS": {"name": "ASML Holding", "sector": "Naamloze vennootschap", "region": "Europe", "exchange": "Euro Stoxx 50"},
    "BAYN.DE": {"name": "Bayer", "sector": "Aktiengesellschaft", "region": "Europe", "exchange": "Euro Stoxx 50"},
    "BBVA.MC": {"name": "BMAD: BBVA", "sector": "BBVA", "region": "Europe", "exchange": "Euro Stoxx 50"},
    "RACE.MI": {"name": "Ferrari", "sector": "Naamloze vennootschap", "region": "Europe", "exchange": "Euro Stoxx 50"},
    "NDA-FI.HE": {"name": "Nasdaq Helsinki: NDA FI", "sector": "Nordea", "region": "Europe", "exchange": "Euro Stoxx 50"},
    "RHM.DE": {"name": "Rheinmetall", "sector": "Aktiengesellschaft", "region": "Europe", "exchange": "Euro Stoxx 50"},
    "SAP.DE": {"name": "SAP", "sector": "Societas Europaea", "region": "Europe", "exchange": "Euro Stoxx 50"},
    "ENR.DE": {"name": "Siemens Energy", "sector": "Aktiengesellschaft", "region": "Europe", "exchange": "Euro Stoxx 50"},
    "VOW.DE": {"name": "Volkswagen Group", "sector": "Aktiengesellschaft", "region": "Europe", "exchange": "Euro Stoxx 50"},
}

ETFS = {
    # ── Broad World ──
    "IWDA.AS":  {"name": "iShares Core MSCI World", "index_tracked": "MSCI World", "ter": 0.0020, "domicile": "Ireland", "category": "Equity World", "region": "World", "exchange": "Euronext"},
    "VWCE.DE":  {"name": "Vanguard FTSE All-World", "index_tracked": "FTSE All-World", "ter": 0.0022, "domicile": "Ireland", "category": "Equity World", "region": "World", "exchange": "XETRA"},
    "URTH":     {"name": "iShares MSCI World ETF", "index_tracked": "MSCI World", "ter": 0.0024, "domicile": "US", "category": "Equity World", "region": "World", "exchange": "NYSE"},

    # ── US Equity ──
    "VUSA.AS":  {"name": "Vanguard S&P 500 UCITS", "index_tracked": "S&P 500", "ter": 0.0007, "domicile": "Ireland", "category": "Equity US Large Cap", "region": "US", "exchange": "Euronext"},
    "CSPX.AS":  {"name": "iShares Core S&P 500 UCITS", "index_tracked": "S&P 500", "ter": 0.0007, "domicile": "Ireland", "category": "Equity US Large Cap", "region": "US", "exchange": "Euronext"},
    "EQQQ.DE":  {"name": "Invesco NASDAQ-100 UCITS", "index_tracked": "NASDAQ-100", "ter": 0.0030, "domicile": "Ireland", "category": "Equity US Tech", "region": "US", "exchange": "XETRA"},
    "SPY":      {"name": "SPDR S&P 500 ETF Trust", "index_tracked": "S&P 500", "ter": 0.0009, "domicile": "US", "category": "Equity US Large Cap", "region": "US", "exchange": "NYSE"},
    "QQQ":      {"name": "Invesco QQQ Trust", "index_tracked": "NASDAQ-100", "ter": 0.0020, "domicile": "US", "category": "Equity US Tech", "region": "US", "exchange": "NASDAQ"},
    "IWM":      {"name": "iShares Russell 2000 ETF", "index_tracked": "Russell 2000", "ter": 0.0019, "domicile": "US", "category": "Equity US Small Cap", "region": "US", "exchange": "NYSE"},
    "VTV":      {"name": "Vanguard Value ETF", "index_tracked": "CRSP US Large Cap Value", "ter": 0.0004, "domicile": "US", "category": "Equity US Value", "region": "US", "exchange": "NYSE"},
    "VUG":      {"name": "Vanguard Growth ETF", "index_tracked": "CRSP US Large Cap Growth", "ter": 0.0004, "domicile": "US", "category": "Equity US Growth", "region": "US", "exchange": "NYSE"},

    # ── European Equity ──
    "MEUD.PA":  {"name": "Amundi MSCI Europe UCITS", "index_tracked": "MSCI Europe", "ter": 0.0015, "domicile": "Luxembourg", "category": "Equity Europe", "region": "Europe", "exchange": "Euronext"},
    "CEU.PA":   {"name": "Amundi Euro Stoxx 50 UCITS", "index_tracked": "Euro Stoxx 50", "ter": 0.0009, "domicile": "France", "category": "Equity Eurozone", "region": "Europe", "exchange": "Euronext"},
    "VEUR.AS":  {"name": "Vanguard FTSE Dev Europe UCITS", "index_tracked": "FTSE Developed Europe", "ter": 0.0010, "domicile": "Ireland", "category": "Equity Europe", "region": "Europe", "exchange": "Euronext"},
    "EZU":      {"name": "iShares MSCI Eurozone ETF", "index_tracked": "MSCI EMU", "ter": 0.0049, "domicile": "US", "category": "Equity Eurozone", "region": "Europe", "exchange": "NYSE"},
    "EWG":      {"name": "iShares MSCI Germany ETF", "index_tracked": "MSCI Germany", "ter": 0.0050, "domicile": "US", "category": "Equity Germany", "region": "Europe", "exchange": "NYSE"},
    "EWQ":      {"name": "iShares MSCI France ETF", "index_tracked": "MSCI France", "ter": 0.0050, "domicile": "US", "category": "Equity France", "region": "Europe", "exchange": "NYSE"},
    "EWU":      {"name": "iShares MSCI UK ETF", "index_tracked": "MSCI United Kingdom", "ter": 0.0050, "domicile": "US", "category": "Equity UK", "region": "Europe", "exchange": "NYSE"},

    # ── Emerging Markets ──
    "VFEM.AS":  {"name": "Vanguard FTSE EM UCITS", "index_tracked": "FTSE Emerging", "ter": 0.0022, "domicile": "Ireland", "category": "Equity Emerging Markets", "region": "Asia", "exchange": "Euronext"},
    "EEM":      {"name": "iShares MSCI Emerging Markets", "index_tracked": "MSCI Emerging Markets", "ter": 0.0068, "domicile": "US", "category": "Equity Emerging Markets", "region": "Asia", "exchange": "NYSE"},
    "VWO":      {"name": "Vanguard FTSE Emerging Markets", "index_tracked": "FTSE Emerging Markets", "ter": 0.0008, "domicile": "US", "category": "Equity Emerging Markets", "region": "Asia", "exchange": "NYSE"},
    "FXI":      {"name": "iShares China Large-Cap ETF", "index_tracked": "FTSE China 50", "ter": 0.0074, "domicile": "US", "category": "Equity China", "region": "Asia", "exchange": "NYSE"},

    # ── Sector ETFs ──
    "XLK":      {"name": "Technology Select Sector SPDR", "index_tracked": "S&P Technology", "ter": 0.0009, "domicile": "US", "category": "Sector Technology", "region": "US", "exchange": "NYSE"},
    "XLF":      {"name": "Financial Select Sector SPDR", "index_tracked": "S&P Financials", "ter": 0.0009, "domicile": "US", "category": "Sector Financials", "region": "US", "exchange": "NYSE"},
    "XLE":      {"name": "Energy Select Sector SPDR", "index_tracked": "S&P Energy", "ter": 0.0009, "domicile": "US", "category": "Sector Energy", "region": "US", "exchange": "NYSE"},
    "XLV":      {"name": "Health Care Select Sector SPDR", "index_tracked": "S&P Health Care", "ter": 0.0009, "domicile": "US", "category": "Sector Healthcare", "region": "US", "exchange": "NYSE"},
    "XLI":      {"name": "Industrial Select Sector SPDR", "index_tracked": "S&P Industrials", "ter": 0.0009, "domicile": "US", "category": "Sector Industrials", "region": "US", "exchange": "NYSE"},

    # ── Thematic ──
    "ICLN":     {"name": "iShares Global Clean Energy", "index_tracked": "S&P Global Clean Energy", "ter": 0.0040, "domicile": "US", "category": "Thematic Clean Energy", "region": "World", "exchange": "NASDAQ"},
    "ARKK":     {"name": "ARK Innovation ETF", "index_tracked": "ARK Innovation", "ter": 0.0075, "domicile": "US", "category": "Thematic Innovation", "region": "US", "exchange": "NYSE"},
    "SOXX":     {"name": "iShares Semiconductor ETF", "index_tracked": "ICE Semiconductor", "ter": 0.0035, "domicile": "US", "category": "Thematic Semiconductors", "region": "US", "exchange": "NASDAQ"},
    "TAN":      {"name": "Invesco Solar ETF", "index_tracked": "MAC Global Solar Energy", "ter": 0.0067, "domicile": "US", "category": "Thematic Solar", "region": "World", "exchange": "NYSE"},

    # ── Fixed Income & Commodities ──
    "GLD":      {"name": "SPDR Gold Shares", "index_tracked": "Gold Spot Price", "ter": 0.0040, "domicile": "US", "category": "Commodity Gold", "region": "World", "exchange": "NYSE"},
    "SLV":      {"name": "iShares Silver Trust", "index_tracked": "Silver Spot Price", "ter": 0.0050, "domicile": "US", "category": "Commodity Silver", "region": "World", "exchange": "NYSE"},
    "TLT":      {"name": "iShares 20+ Year Treasury Bond", "index_tracked": "ICE US Treasury 20+ Year", "ter": 0.0015, "domicile": "US", "category": "Bond US Long Term", "region": "US", "exchange": "NASDAQ"},
}

# Combined universe
ALL_TICKERS = list(STOCKS.keys()) + list(ETFS.keys())

# ─── Market Indices ───
INDICES = {
    "^GSPC":     {"name": "S&P 500"},
    "^IXIC":     {"name": "NASDAQ Composite"},
    "^DJI":      {"name": "Dow Jones"},
    "^FCHI":     {"name": "CAC 40"},
    "^GDAXI":    {"name": "DAX"},
    "^STOXX50E": {"name": "Euro Stoxx 50"},
    "^FTSE":     {"name": "FTSE 100"},
    "^IBEX":     {"name": "IBEX 35"},
    "FTSEMIB.MI": {"name": "FTSE MIB"},
    "^N225":     {"name": "Nikkei 225"},
}

# ─── Horizons ───
HORIZONS = {
    "short":  {"days": 30, "label": "Short-term (~30 days)"},
    "medium": {"days": 252, "label": "Medium-term (~12 months)"},
    "long":   {"days": 756, "label": "Long-term (~3 years)"},
}

# ─── Data Fetch Settings ───
HISTORY_PERIOD = "5y"  # 5 years of daily data
